Feature/homework 10 1
mrDrauzer/pythonproject pull request #1
Opened 2024-09-23 21:38 UTC by mrDrauzer

2024-09-25 22:10 UTC, mrDrauzer commented
изминения в соответствии с коментариями

2024-09-26 16:26 UTC, painassasin requested changes

2024-09-26 16:26 UTC, painassasin commented on src/processing.py
> +list_pr = [
Весь исполняемый код из модулей нужно убрать, иначе нельзя будет импортировать функции написанные в нем (весь код ниже)

2024-09-26 16:26 UTC, painassasin commented on src/processing.py
> +    except Exception:
Тут ошибки быть не должно, а если она и есть, то ее не нужно перехватывать

2024-09-26 18:57 UTC, mrDrauzer commented
Вроде все поправил.

2024-09-27 13:44 UTC, painassasin approved these changes

2024-10-02 13:31 UTC, merged